import React from 'react';
import StoryView from './StoryView.jsx';
import DownloadMenu from './DownloadMenu.jsx';
import {
  exportDiagramAsSvg, exportDiagramAsPng, exportDiagramAsJpg,
  exportDiagramAsPdf, exportMermaidSource, downloadBlob
} from '../utils/diagramExport.js';
import { buildAllSequenceDiagrams } from '../utils/uml.js';

/**
 * ManagementOnlyView — the standalone "executive" route.
 *
 * Rendered when the URL contains `?view=management`. Strips out the editor
 * (palette, component list, connection list, canvas tools, baseline/diff,
 * cloud controls). Leadership sees only the 4-tab Management dashboard.
 *
 * A small top bar offers:
 *   • the architecture title
 *   • a "Download" menu (PNG/SVG/PDF/JSON/Mermaid)
 *   • an "Open full editor" link that drops the `view=management` param
 */
export default function ManagementOnlyView({ builder, filenameBase }) {
  const { title, components, connections, allTypes, mermaid } = builder;

  const sequences = React.useMemo(
    () => buildAllSequenceDiagrams({ components, connections, allTypes }),
    [components, connections, allTypes]
  );

  const exportJson = () => {
    downloadBlob(new Blob([builder.exportJson()], { type: 'application/json' }), `${filenameBase}.archivise.json`);
  };

  const openFullEditor = () => {
    const url = new URL(window.location.href);
    url.searchParams.delete('view');
    window.location.href = url.toString();
  };

  const downloadActions = [
    { label: 'Architecture JSON',      onClick: exportJson },
    { label: 'Diagram — SVG (vector)', onClick: () => exportDiagramAsSvg(mermaid, filenameBase) },
    { label: 'Diagram — PNG (2×)',     onClick: () => exportDiagramAsPng(mermaid, filenameBase, 2) },
    { label: 'Diagram — PNG (4×)',     onClick: () => exportDiagramAsPng(mermaid, filenameBase, 4) },
    { label: 'Diagram — JPG',          onClick: () => exportDiagramAsJpg(mermaid, filenameBase, 2) },
    { label: 'Diagram — PDF (print)',  onClick: () => exportDiagramAsPdf(mermaid, title) },
    { label: 'Mermaid source (.mmd)',  onClick: () => exportMermaidSource(mermaid, filenameBase) }
  ];

  return (
    <div className="mgmt-only">
      <header className="mgmt-only-header">
        <div className="mgmt-only-brand">
          <strong>Archivise</strong>
          <span className="mgmt-only-pill">Executive view</span>
        </div>
        <div className="mgmt-only-title">
          <h1>{title || 'Untitled architecture'}</h1>
          <p className="muted">Read-only stakeholder dashboard. No editing tools.</p>
        </div>
        <div className="mgmt-only-actions">
          <DownloadMenu
            className="secondary-btn"
            label="⬇ Download"
            disabled={components.length === 0}
            actions={downloadActions}
          />
          <button type="button" className="link-btn" onClick={openFullEditor}>Open full editor →</button>
        </div>
      </header>

      <main className="mgmt-only-main">
        {components.length === 0 ? (
          <div className="mgmt-only-empty">
            <h2>Nothing to show yet</h2>
            <p className="muted">This shared link doesn’t contain any architecture data.</p>
            <button type="button" className="primary-btn" onClick={openFullEditor}>Open the editor</button>
          </div>
        ) : (
          <StoryView
            title={title}
            flows={sequences}
            components={components}
            connections={connections}
            allTypes={allTypes}
          />
        )}
      </main>

      <footer className="mgmt-only-footer">
        Generated by <strong>Archivise</strong> · Plain-English architecture for leadership · No engineering knowledge required.
      </footer>
    </div>
  );
}
